version: "3.3"

services:

  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.email=chrisiivix@gmail.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ticketbooth:
    image: registry.gitlab.com/diivix/ticketbooth:develop
    container_name: ticketbooth
    restart: unless-stopped
    environment:
      SERVICE_NAME: ticketbooth
      SERVICE_TAGS: production
    working_dir: /app
    volumes:
      - /data/ticketbooth:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ticketbooth.middlewares=ticketbooth-mw@docker"
      - "traefik.http.routers.ticketbooth.rule=Host(`diivix.com`)&&PathPrefix(`/auth`)"
      - "traefik.http.routers.ticketbooth.entrypoints=websecure"
      - "traefik.http.routers.ticketbooth.tls.certresolver=mytlschallenge"
      - "traefik.http.services.ticketbooth.loadbalancer.server.port=3080"
      - "traefik.http.middlewares.ticketbooth-mw.replacepathregex.regex=^/auth/"
      - "traefik.http.middlewares.ticketbooth-mw.replacepathregex.replacement=/"
